### PR TITLE
re- worked some of the completed uploads cache

### PR DESCRIPTION
**Pull request by nmrshll**
I'm not quite satisfied with that yet, but it runs, it's just so you can already have a look, I'll finish this after the week-end

I'm now using only a hash as cache key, it's a fast one though, it doesn't seem to have much impact on upload speed (at least compared to how slow uploading is, plus with rate limiting)

### CODE REVIEW

**Comment by nhorvath** [comment]
Ok I'll see how it performs tomorrow.

**Comment by nhorvath** [comment]
Oh, right i'm going to have to reupload everything to rebuild the uploaded db. It'll be a few days before I can get back to you.

**Comment by nhorvath** [comment]
@nmrshll Since you switch to the mimetype from file extension you will need to blacklist some image types that don't work with google photos. For example: 
```
2018/12/15 10:59:38 Uploading Pamphlet.psd
c37679f5
2018/12/15 10:59:38 leveldb: not found
2018/12/15 10:59:42 failed uploading image
 --- at /home/nick/go/src/github.com/nmrshll/gphotos-uploader-cli/upload/fileUpload.go:33 (StartFileUploadWorker.func1) ---
Caused by: failed uploading image
 --- at /home/nick/go/src/github.com/nmrshll/gphotos-uploader-cli/upload/fileUpload.go:53 (FileUpload.upload) ---
Caused by: status message should be OK, found: NOT_IMAGE: There was an error while trying to create this media item.
 --- at /home/nick/go/src/github.com/nmrshll/google-photos-api-client-go/lib-gphotos/client.go:143 (Client.UploadFile) ---
exit status 1
```

**Comment by nhorvath** [comment]
I think you should add back the mtime check. If a file name is the same and the mtime is the same it's unlikely that it's a false positive. Now that you've added movies, hashing movie files takes quite a while.

**Comment by nhorvath** [comment]
I changed IsImage to this:
```
// IsImage asserts file at filePath is an image
func IsImage(filePath string) bool {
	buf, err := filesystem.BufferFromFile(filePath)
	if err != nil {
		return false
	}

	kind, _ := filetype.Image(buf)

	return kind != filetypes.Unknown && kind != filematchers.TypePsd && kind != filematchers.TypeTiff && kind != filematchers.TypeCR2
}
```

**Comment by nhorvath** [comment]
I had to restart today after the token expired. The hash is for sure slower than checking mtime, and has the side effect of taking iowait up very high on my server. I'm going to add back the mtime check, but use your hash as the fallback for modified files.

**Comment by nhorvath** [comment]
Oh, I see what you did... storing the hash as the key and merely checking for it is a bad idea. In a large photoset it's very possible that two photos will hash to the same value and you will miss files. The mere existence of the hash value in the cache is not good enough to ensure everything gets uploaded.

**Comment by nmrshll** [comment]
> Oh, I see what you did... storing the hash as the key and merely checking for it is a bad idea. In a large photoset it's very possible that two photos will hash to the same value and you will miss files. The mere existence of the hash value in the cache is not good enough to ensure everything gets uploaded.

What do you mean here ? Is it not a goal to not upload duplicates ? Or do you mean if the same file is in two different folders it should be uploaded to different albums for example ?

Other than that I agree with everything else. Let's switch back to the mtime check. And I really like the  streaming hashing thing you added. Thanks a lot !

**Comment by nhorvath** [comment]
I mean that by design, 2 different files can hash to the same values. You're going from megabytes of information to 32 bits of info (granted there are 4 billion possibilities if your data was perfectly distributed, but that's unlikely). The difference between a straight hash like this and your perceptual hash is which things hash to the same value: in a normal hash it will be 2 vastly different things that match and in the perceptual hash it will be 2 very close things that hash. That's why the former is good for file verification, because slight changes cause very different hashes.

**Comment by nmrshll** [comment]
Oh that's the main thing that I changed since you first opened the pull request:
now the hash used by the completed uploads cache is a straight hash and not a perceptual one, it should hash to different values if only one byte of the input data is different. I think even with 32 bits we can ignore collisions.

I'm trying out your latest version of the uploader at the moment, but all seems good to merge to me !

**Comment by nhorvath** [comment]
I actually had a collision (false positive) which is what made me discover
it. I'm sorry I can't remember the 2 files as examples but one uploaded
that wouldn't when i switched back to using the file path as the leveldb key.

**Pull request merged**
